### PR TITLE
Fix image resize on osx.

### LINKED ISSUE #1: Broken on OS X
It looks like the line endings this is saved to npm with (CRLF) have some issues on OS X:
image1447687549307
I manually fixed the line endings, but it seems to randomly get errors during image conversion and fail. I suspect some of these errors will happen on Windows as well (will follow up to confirm).

If there aren't any image conversion errors, it doesn't launch phantomjs and just hangs.

Also, running just `hwa` fails because the tool can't find the documentation.

Was running NodeJS 5.0 and npm 3.3.9

### PR DESCRIPTION
**Pull request by jdalton**
This PR fixes image resize on osx. Closes #1.

### CODE REVIEW

File: src/cli.ts [hunk 1]
```diff
@@ -12,11 +12,9 @@ import cloudAppx = require("./cloudAppx");
 import crxConverter = require("./crxConverter");
 import webConverter = require("./webConverter");
 
-var archiver = require("archiver");
```
Comment (jdalton) [inline src/cli.ts]: These weren't used.
